# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2dfbda6af512f0f4a58b7f89bbe30bad6a0b06e23143e96554c6a9b728128c7e40a526255d741c299db5615d85c0a4696d9b3acc8e9314a1cb669e26e3dab17f

test:
  secret_key_base: 7483d72e49abf218b357c8e6602037bb99f126d03e62330aae394699860c4c043ee3bae2fa8332a55c1913fcdece341e3eb7c9547694318367637ec5d6d7f3c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
